Ionic+Vue Example
auth0-samples/auth0-ionic-samples pull request #221
Opened 2022-06-17 07:25 UTC by ArcticGizmo

I have created a sample project for  Ionic+Vue3.
It is a combination of Ionic+React and the SPA Vue example.

I have tested it in the browser and on an android device, but not on iOS

2022-06-17 10:44 UTC, stevehobbsdev commented
Thanks for this PR @ArcticGizmo, looks very comprehensive 🎉 

Before I do a deep dive into reviewing it, I will say that our samples typically are companions for our quickstarts that exist on our docs site ([example for Ionic React](https://auth0.com/docs/quickstart/native/ionic-react/interactive)), but we don't currently have this for Vue.

Let me have a discussion internally around timelines on that and how we want to move forward with this PR, and come back to you.

2022-06-18 14:27 UTC, ArcticGizmo commented
@stevehobbsdev I have created a PR to add the [quickstart guide](https://github.com/auth0/docs/pull/10107) as I thought it might help out :)

2023-01-18 21:36 UTC, frederikprijck approved these changes
Thanks for all the work here! 🚀 

Sorry it took so long to get to this PR, but we wanted to wait for when we release v2 of Auth0-Vue.

I will merge this in a different branch, as we will need to patch a few things for v2 of our SDK, but this should land in master anytime soon.

2023-01-18 21:45 UTC, frederikprijck requested changes

2023-01-18 21:45 UTC, frederikprijck commented on .circleci/config.yml
> +    steps:
```suggestion
    steps:
      - attach_workspace:
          at: .
```

2023-01-18 21:48 UTC, frederikprijck approved these changes

2023-01-18 21:48 UTC, merged